# Generated by Django 2.0.4 on 2018-05-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20180531_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
