# Generated by Django 2.0.4 on 2018-06-01 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0007_auto_20180531_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='jugador',
        ),
        migrations.AddField(
            model_name='nomina',
            name='jugador',
            field=models.ManyToManyField(to='basket.Player'),
        ),
    ]
